/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Invoked */

#ifndef _Included_Invoked
#define _Included_Invoked
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Invoked
 * Method:    getTid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Invoked_getTid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
