/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Multithread */

#ifndef _Included_Multithread
#define _Included_Multithread
#ifdef __cplusplus
extern "C" {
#endif
#undef Multithread_MIN_PRIORITY
#define Multithread_MIN_PRIORITY 1L
#undef Multithread_NORM_PRIORITY
#define Multithread_NORM_PRIORITY 5L
#undef Multithread_MAX_PRIORITY
#define Multithread_MAX_PRIORITY 10L
/*
 * Class:     Multithread
 * Method:    lbrRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Multithread_lbrRecord
  (JNIEnv *, jobject);

/*
 * Class:     Multithread
 * Method:    getTid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Multithread_getTid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
